# Generated by Django 3.2.6 on 2021-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_date', models.DateField(auto_now=True)),
                ('event_image_icon', models.ImageField(default='prod_default_image.png', upload_to='event_icons/')),
                ('event_type', models.CharField(choices=[('DJ', 'Django'), ('AN', 'Android'), ('PY', 'Python')], max_length=30)),
                ('production_icon', models.ImageField(default='prod_default_image.png', upload_to='event_icons/')),
                ('event_github_link', models.CharField(default='No', max_length=50)),
                ('event_production_link', models.CharField(default='No', max_length=50)),
                ('event_title_date_color', models.CharField(default='ff927b', max_length=6)),
                ('event_description', models.TextField(default='', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(default='', max_length=50)),
                ('tech_link', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
