# Generated by Django 3.2.6 on 2021-09-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='techs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.tech'),
            preserve_default=False,
        ),
    ]
