# Generated by Django 3.2.6 on 2021-09-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_techs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='techs',
        ),
    ]
