# Generated by Django 3.2.6 on 2021-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_tech_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_screenshot_1',
            field=models.ImageField(default='prod_default_image.png', upload_to='event_icons/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_screenshot_2',
            field=models.ImageField(default='prod_default_image.png', upload_to='event_icons/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_screenshot_3',
            field=models.ImageField(default='prod_default_image.png', upload_to='event_icons/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_screenshot_4',
            field=models.ImageField(default='prod_default_image.png', upload_to='event_icons/'),
        ),
    ]
