# Generated by Django 3.2.6 on 2021-09-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210927_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_screenshot_1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_screenshot_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_screenshot_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_screenshot_4',
        ),
    ]
