# Generated by Django 3.2.6 on 2021-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_doc_link',
            field=models.CharField(default='No', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_github_link',
            field=models.CharField(default='No', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_production_link',
            field=models.CharField(default='No', max_length=150),
        ),
    ]
