# Generated by Django 3.2.6 on 2021-09-28 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_event_doc_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_res_link', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('res_name', models.CharField(default='', max_length=50)),
                ('res_link', models.CharField(default='', max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
