# Generated by Django 3.2.6 on 2021-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_postres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postres',
            name='post_res_link',
        ),
        migrations.AddField(
            model_name='event',
            name='post_res_link',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
