# Generated by Django 3.2.6 on 2021-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20210929_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_doc_file',
            field=models.FileField(default='', upload_to='event_dia_doc//%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
