# Generated by Django 3.2.6 on 2021-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_event_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_doc_file',
            field=models.FileField(upload_to='event_dia_doc/%Y/%m/%d/'),
        ),
    ]
