# Generated by Django 3.2.6 on 2021-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_event_event_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_doc_file',
            field=models.FileField(blank=True, upload_to='event_dia_doc/%Y/%m/%d/'),
        ),
    ]
