# Generated by Django 3.2.6 on 2021-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_event_event_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_doc_file',
            field=models.CharField(default='No', max_length=150),
        ),
    ]
